### ISSUE TITLE
Bug: Uploading new version of script with an edited character causes a 500 error

### ISSUE THREAD

**Issue by nabergh** [AdmiralGT/botc-scripts#516]
**Describe the bug**
Uploading a new version of my [script](https://botcscripts.com/script/6407/1.0.1) caused a 500 error. The only change I made was replacing the `name` field of the Witch character from `witch` to `Witch`.

**When did it happen**
Within the past 10 minutes.

**To Reproduce**
1. Download the 1.0.1 version json from this [script](https://botcscripts.com/script/6407/1.0.1)
2. Change `"name": "witch"` to `"name": "Witch"`
3. Upload the new version
The 500 error should show right after submitting the new version.

**Comment by AdmiralGT** [comment]
Thanks for the report. This has now been fixed in https://github.com/AdmiralGT/botc-scripts/pull/517 which should be deployed shortly. I tested your use case explicitly so I'm hopeful this will resolve the issue but feel free to re-open if this persists to be a problem.

**Comment by nabergh** [comment]
I don't have permissions to reopen the issue but I can confirm that the issue persists for me @AdmiralGT

**Comment by AdmiralGT** [comment]
Ah sorry, this time I think it is fixed. Sorry about that.

**Comment by nabergh** [comment]
It is! Thanks
